#!/bin/bash
apt-get update
apt-get -y install tmux

echo "# remap prefix from 'C-b' to 'C-a'"     > /home/$SUDO_USER/.tmux.conf
echo "unbind C-b"                             >> /home/$SUDO_USER/.tmux.conf
echo "set-option -g prefix M-Space"           >> /home/$SUDO_USER/.tmux.conf
echo "bind-key M-Space send-prefix"           >> /home/$SUDO_USER/.tmux.conf
echo "set -g default-terminal \"screen-256color\"" >> /home/$SUDO_USER/.tmux.conf

apt-get -y install neovim
#Installing Plug for Nvim
mkdir -p /home/$SUDO_USER/.local/share/nvim/site/autoload
curl -fLo /home/$SUDO_USER/local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
nvim +'PlugInstall --sync' +qa
apt-get -y install ranger
apt-get upgrade
